env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - vue
plugins:
  - vue
rules: {
  vue/multi-word-component-names: 'off',
  "@typescript-eslint/explicit-function-return-type": "off",
}
